// <auto-generated />
using KiemTraMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiemTraMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250526062717_Create_Tables_buikhanhtoan")]
    partial class Create_Tables_buikhanhtoan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KiemTra2425.Models.buikhanhtoan", b =>
                {
                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.HasKey("FullName");

                    b.ToTable("buikhanhtoan");
                });
#pragma warning restore 612, 618
        }
    }
}
